"""new fields in user model

Revision ID: 34785eb5e000
Revises: 496125c27921
Create Date: 2025-03-24 14:05:06.857282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34785eb5e000'
down_revision = '496125c27921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
